apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: ecommerce_db
    user: user
    secureJsonData:
      password: password
    jsonData:
      sslmode: 'disable'
      postgresVersion: 15
      timescaledb: false
